"""alembic setup age

Revision ID: a01396960e72
Revises: 5bba967044bc
Create Date: 2024-04-16 22:24:36.535886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a01396960e72'
down_revision: Union[str, None] = '5bba967044bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
